### ISSUE TITLE
I want to know when I finished install this game how to be played?

### ISSUE THREAD

**Issue by lotu5david** [MrEliasen/path-to-power-client#1]
## Is this a bug report?

(write your answer here)

## Environment Information

Operating System: 
Browser and version: 

## Steps to Reproduce

1.
2.
3.

## Expected Behavior

(Write what you expected it would behave.)

## Actual Behavior

(Write what happened. Add screenshots please!)

**Comment by MrEliasen** [comment]
I have just update the [Wiki](https://github.com/MrEliasen/path-to-power-client/wiki) where you can learn more about how to play the game.

Hope this helps!
